#!/usr/bin/env python3
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config.py"
TEMPLATE_PATH = ROOT / "config_template.py"

def prompt(default: str, label: str) -> str:
    val = input(f"{label} [{default}]: ").strip()
    return val or default

def main():
    print("This will create or update config.py in the repo root.")
    if not TEMPLATE_PATH.exists():
        print("config_template.py missing, creating a basic template...")
        TEMPLATE_PATH.write_text(
            """
WIFI_SSID = "your-ssid"
WIFI_PASSWORD = "your-password"
CHECKWX_API_KEY = "your-api-key"
LED_PIN = 14
LED_COUNT = 50
REFRESH_MINUTES = 15
WEBREPL_ENABLED = False
""".strip()
        )

    ssid = prompt("your-ssid", "Wi-Fi SSID")
    pw = prompt("your-password", "Wi-Fi Password")
    api = prompt("your-api-key", "CheckWX API Key")
    led_pin = prompt("14", "LED GPIO Pin")
    led_count = prompt("50", "LED Count")
    refresh = prompt("15", "Refresh minutes")
    webrepl = prompt("False", "Enable WebREPL at boot? (True/False)")

    content = f"""
# Generated by tools/setup_config.py
WIFI_SSID = {ssid!r}
WIFI_PASSWORD = {pw!r}
CHECKWX_API_KEY = {api!r}
LED_PIN = int({led_pin})
LED_COUNT = int({led_count})
REFRESH_MINUTES = int({refresh})
WEBREPL_ENABLED = {webrepl}
""".lstrip()
    CONFIG_PATH.write_text(content)
    print(f"Wrote {CONFIG_PATH}")

    print("\nOptional: push config.py to the device now.")
    do_push = input("Push now? (y/N): ").strip().lower() == "y"
    if do_push:
        port = os.environ.get("PORT")
        if not port:
            # Try autodetect
            import glob
            ports = glob.glob("/dev/tty.usb*") + glob.glob("/dev/tty.SLAB*") + glob.glob("/dev/tty.wchusb*")
            port = ports[0] if ports else None
        if not port:
            print("Could not detect serial port automatically. Set PORT env var and re-run push.")
            return
        os.system(f"mpremote connect {port} fs cp {CONFIG_PATH} :config.py")
        print("Pushed config.py to device.")

if __name__ == "__main__":
    main()
